[project]
name = "triton-pretask"
version = "0.1.0"
description = "Triton pretask for PLCT."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch>=2.5.1",
    "triton>=3.1.0",
]

[tool.uv]
index-url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
